[package]
name = "zinnia"
version = "0.1.0"
authors = ["Darrell Pittman <darrellppittman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.5.0"
lazy_static = "1.4.0"
